### ISSUE TITLE
Build System Support

### ISSUE THREAD

**Issue by napperley** [openfaas/templates#35]
With larger projects there is a need to use a build system (with some programming languages). In the case of Kotlin (as a example) Gradle is the main build system used. Gradle has a build structure convention (**src/main/kotlin**, **src/test/kotlin** etc) which is used by projects that use the build system.

## Expected Behaviour

Unsure what the expected behaviour would be since the OpenFaaS template structure assumes a programming language doesn't use a build system, and that the build process is completely handled in a Docker image.

## Current Behaviour

As it currently stands a template cannot use a build system, especially one that has build structure conventions that need to be followed in a project.

## Context

There needs to be a general consensus (way forward) on how to handle templates where a build system is needed or required by a programming language.

**Comment by iyovcheva** [comment]
Hi @napperley,

I didn't test, but my first proposal for this to be achieved is to edit the template's Dockerfile to install and configure the build tool and execute tasks.

This can also be done using `build-args`.

The best solution IMO is to add `build_system` build option similar to [templates#28](https://github.com/openfaas/templates/issues/28)

A `template.yml` can contain
```
build-options:
  - name: build_system
     commands:
       win: 
         - scoop install gradle && \
         - ....
       lin: 
         - sdk install gradle 4.6
         - ....
       osx:
         - brew install gradle
         - ...
```

cc @alexellis @rgee0
